### ISSUE TITLE
Adding Payment Webhooks

### ISSUE THREAD

**Issue by antoinecharbonneau** [kcable194/squareup#7]
It would be useful to add payment's webhooks now that the Checkout API has been added to receive notifications about payments being processed.

I will try to do that today

**Comment by kcable194** [comment]
That would be great! Thank you

**Comment by antoinecharbonneau** [comment]
One thing I am wondering is since the webhooks for creation and updates of payments have the same interface with different documented names (in the end the structs have the exact same format, both ending up with a `Payment` object nested in the API, should we unify the structs into a single struct where essentially only the event type would differ? I will publish an example as I believe it would make sense to proceed as such since the documentation doesn't mention any single difference in the data model being sent.

**Comment by kcable194** [comment]
That makes sense to me. I ended up only using one type of booking webhook (Create) for a project I'm working on. Since they're essentially the same structs, I match on the event type (Create or Update) to handle my business logic. 

I mainly went with the double implementation to match Squares docs. We'll need to add better examples and documentation around using the unified webhook structs for multiple events, which is totally fine. We may also need to be prepared to split them back out if Square ever changes their implementations.

**Comment by antoinecharbonneau** [comment]
If we were to split them, I think the best way to do it would be to use Serde's adjacently tagged enums: https://serde.rs/enum-representations.html
